title	Arch Linux
linux	/vmlinuz-linux
initrd	/amd-ucode.img
initrd	/initramfs-linux.img
options	cryptdevice=UUID=267f1264-8199-4560-97ce-32849081972f:cryptlvm root=/dev/vg0/root rootflags=subvol=@ rootfstype=btrfs zswap.enabled=0 rw quiet splash nvidia_drm.modeset=1
